name: Backend CI

on:
  push:
    paths:
      - "backend/**"
      - "tests/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    paths:
      - "backend/**"
      - "tests/**"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          # Tools for CI only
          pip install ruff==0.3.4 pytest

      - name: Ruff Lint
        run: |
          # Run ruff but do not fail the build on lint errors yet
          ruff check . || true

      - name: Run tests
        run: |
          pytest -q